### ISSUE TITLE
Apresentação

### ISSUE THREAD

**Issue by raulikeda** [lobaoar/Ativos_Digitais#2]
Por favor, providenciar a apresentação e o link para o vídeo no repositório.

**Comment by lobaoar** [comment]
[Uploading Projeto final - Blockchain (1).pptx…]()

**Comment by lobaoar** [comment]
Boa noite Raul! Tudo bem?
O vídeo ja esta no powerpoint precisa que eu suba em outro lugar?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by raulikeda** [comment]
Não precisa. Obrigado

**Comment by lobaoar** [comment]
Eu que agradeço

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
